/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    led_init();
    switch_init();
    int c = 0;
    while (1)
    {
        if (switch_status() == 1)
        {
            switch (c)
            {
                case 0:
          led_one();
                    c = 1;
                    break;
                case 1:
          led_two();
                    c = 2;
                    break;
                case 2:
          led_three();
                	c=0;
                     break;
                case 3:
          led_four();
                    c = 0;
                    break;
          led_three();
                    c = 3;
                default:
                    c = 0;
                    break;
            }
            while (switch_status() == 1);
        }
    }
}








